name: Publish

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
    
      - name: NPM Build Install Lerna
        shell: bash
        run: npm install -g lerna
      - name: NPM Build Install TypeScript 
        shell: bash
        run: npm install -g typescript tsdoc
      
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(git describe --abbrev=0 --tags)
   

 
      - name: Configure Git	
        shell: bash	
        env:	
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}	
        run: |	
          git config --global user.email "dangonggm@gmail.com"	
          git config --global user.name "gong4494"	
      - name: Fetch tag and check master
        shell: bash	
        env:	
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}	
        run: |
          git fetch --prune --unshallow --tags

      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}