name: Push tag

on:
  push:
    branches: [ master ]
 
jobs:
  create-tag:   
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Bump and push tag
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch